### ISSUE TITLE
SDK not compiling in swift 3.0.2

### ISSUE THREAD

**Issue by ssauravv22** [citruspay/citruspay-ios-sdk#14] opened 2016-12-30 21:31 UTC
Unable to compile in swift 3.0.2, 
"Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2"
I think the problem is with pre-built binaries.

**Comment by krishnans** [comment] 2016-12-31 12:38
i think the problem is with the CitrusGraphics.framework with is built using swift 3.0.  I am having the same issue.

**Comment by ssauravv22** [comment] 2016-12-31 14:21
Yes, the problem is with CitrusGraphics module. I am able to compile other frameworks.
By any chance did you find a solution to include it in latest Swift version?

**Comment by krishnans** [comment] 2016-12-31 17:41
as of now i am using old version "4.0.2".  It Compiles without any issue

**Comment by ssauravv22** [comment] 2017-01-01 04:50
Thanks Mate!

**Comment by mukesh122** [comment] 2017-01-02 05:35
Guys, thanks for the comment. This issues has been take up already & you will be get fixed into coming release.
Thanks.

**Comment by mukesh122** [comment] 2017-01-05 11:54
FYI @ssauravv22  @krishnans  - This issues has been fixed into latest CitrusGraphics SDK Version 1.1

**Closed** 2017-01-10 10:21 UTC

**Comment by ssauravv22** [comment] 2017-01-11 05:26
@mukesh122 
We are facing the same issue in CitrusPay.framework while archiving the app.
